repository: sproogen/resume-theme
favicon: images/favicon.ico

version: 2

name: Rohan Rathore
title: Data Engineer | Bengaluru, India
phone_title: Contact 
phone: rohan.rathore93@gmail.com
email_title: Status
email: Verified Expert

darkmode: never

twitter_username: rohanredtj
github_username:  rohanredtj
linkedin_username: rohanredtj
instagram_username: rohanredtj

additional_links:
- title: Hire Rohan
  icon: fas fa-briefcase
  url: https://www.upwork.com/freelancers/~01ee871ca78c1a805c

about_profile_image: images/profile.jpg
about_content: | # this will include new lines to allow paragraphs

  ## Expertise
  <span class="block-main"><svg width="12" height="12" viewBox="0 0 14 14" fill="currentColor" xmlns="http://www.w3.org/2000/svg"><path d="m7 10.5-4.114 2.163.785-4.581L.343 4.837l4.6-.669L7 0l2.057 4.168 4.6.669-3.328 3.245.785 4.581z"></path></svg>Data Engineering</span> <span class="block-secondary">Software Engineering</span> <span class="block-secondary">Python</span>

  ## Bio
  Hi, I'm Mike, a senior technologist with over a decade of experience in building and scaling products. Over the past ten years, I've specialized in data engineering, full-stack web development, and product management. I'm a natural problem solver capable of mastering complex subjects quickly and focusing on delivering real value.

  ## Experience
  <span class="block-secondary">Software Engineering - 15 years</span> <span class="block-secondary">Product Management -10 years</span>

  ## Portfolio Projects
  [Data Engineering](#data-engineering-projects), [Data Science](#data-science-projects)

  ## Education
  - [ReturnBear](#) - B2B Product Management, Django, React Native, React, Sales
  - [Parse.ly](#) - Product Management, B2B Product Management, Data Engineering
  - [Globe and Mail](#) - Apache Pig, Hadoop, Amazon Elastic MapReduce (EMR), Web Analytics

  ## Certifications
  - [ReturnBear](#)

  ## Skills
  - **Libraries/APIs** - Pandas, PySpark

  ## Preferred Environment
  Visual Studio Code (VS Code), Google Colab, MacOS

content:
  - title: Data Engineering Projects
    layout: list
    content:
      - layout: left
        title: Project Name A
        sub_title: Job title
        caption: Date Range (eg. November 2016 - present)
        link: github.com/sproogen
        link_text: Project Website
        # additional_links:
        #   - title:  sproogen/modern-resume-theme
        #     icon: fab fa-github
        #     url: github.com/sproogen/modern-resume-theme
        #   - title:  Github page for project (eg. sproogen/modern-resume-theme)
        #     icon: fab fa-github
        #     url: Link to project (eg. sproogen.github.io/modern-resume-theme)
        quote: >
          This is probably one of the greatest apps ever created, if you don't agree you're probably wrong.
        description: | # this will include new lines to allow paragraphs
          I started this project as a way if learning <mark>React</mark> and it has since grown into a fully fledged app. I have learned many skills through this and been I'm very proud of having this in my portfolio. If you don't have a project as awesome as this I would advise you make one.

      - layout: left
        title: Project Name B
        sub_title: Job title
        caption: Date Range (eg. November 2016 - present)
        link: github.com/sproogen
        link_text: Project Website
        quote: >
          This is probably one of the greatest apps ever created, if you don't agree you're probably wrong.
        description: | # this will include new lines to allow paragraphs
          I started this project as a way if learning <mark>React</mark> and it has since grown into a fully fledged app. I have learned many skills through this and been I'm very proud of having this in my portfolio. If you don't have a project as awesome as this I would advise you make one.

  - title: Data Science Projects
    layout: list
    content:
      - layout: left
        title: Project Name A
        sub_title: Job title
        caption: Date Range (eg. November 2016 - present)
        link: github.com/sproogen
        link_text: Project Website
        quote: >
          This is probably one of the greatest apps ever created, if you don't agree you're probably wrong.
        description: | # this will include new lines to allow paragraphs
          I started this project as a way if learning <mark>React</mark> and it has since grown into a fully fledged app. I have learned many skills through this and been I'm very proud of having this in my portfolio. If you don't have a project as awesome as this I would advise you make one.

      - layout: left
        title: Project Name B
        sub_title: Job title
        caption: Date Range (eg. November 2016 - present)
        link: github.com/sproogen
        link_text: Project Website
        quote: >
          This is probably one of the greatest apps ever created, if you don't agree you're probably wrong.
        description: | # this will include new lines to allow paragraphs
          I started this project as a way if learning <mark>React</mark> and it has since grown into a fully fledged app. I have learned many skills through this and been I'm very proud of having this in my portfolio. If you don't have a project as awesome as this I would advise you make one.


# Footer
footer_show_references: false
# references_title: References on request (Override references text)

# Build settings
remote_theme: sproogen/resume-theme

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag
